// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/reverny/kratos-mono/services/inventory/internal/biz"
	"github.com/reverny/kratos-mono/services/inventory/internal/conf"
	"github.com/reverny/kratos-mono/services/inventory/internal/data"
	"github.com/reverny/kratos-mono/services/inventory/internal/server"
	"github.com/reverny/kratos-mono/services/inventory/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	inventoryRepo := data.NewInventoryRepo(dataData, logger)
	inventoryUsecase := biz.NewInventoryUsecase(inventoryRepo, logger)
	inventoryService := service.NewInventoryService(inventoryUsecase)
	grpcServer := server.NewGRPCServer(confServer, inventoryService, logger)
	httpServer := server.NewHTTPServer(confServer, inventoryService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
